import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body >
      <div>{children}</div>
      <div>{modal}</div>
      </body>
    </html>
  );
}
